include ../../mak/UserDefine.mak
include Srcs.mak

INCLUDE += -I../inc -I../../osal/inc -I../../container/inc

all:
	@make build_objs

clean:
	@make clean_objs

include ../../mak/Rules.mak
